export const ANTROPOLOGIA = 'antropologia',
    ARMAS_DE_FUEGO_ARMA_CORTA = 'armas_de_fuego_arma_corta',
    ARMAS_DE_FUEGO_FUSIL_ESCOPETA = 'armas_de_fuego_fusil_escopeta',
    ARMAS_DE_FUEGO_CUSTOM = 'armas_de_fuego_custom',
    ARQUEOLOGIA = 'arqueologia',
    ARTE_ARTESANIA_CUSTOM = 'arte_artesania_custom',
    ARTE_ARTESANIA_CUSTOM_2 = 'arte_artesania_custom_2',
    ARTE_ARTESANIA_CUSTOM_3 = 'arte_artesania_custom_3',
    BUSCAR_LIBROS = 'buscar_libros',
    CERRAJERIA = 'cerrajeria',
    CHARLATENERIA = 'charlateneria',
    CIENCIA_CUSTOM = 'ciencia_custom',
    CIENCIA_CUSTOM_2 = 'ciencia_custom_2',
    CIENCIA_CUSTOM_3 = 'ciencia_custom_3',
    CIENCIAS_OCULTAS = 'ciencias_ocultas',
    COMBATIR_PELEA = 'combatir_pelea',
    COMBATIR_CUSTOM = 'combatir_custom',
    COMBATIR_CUSTOM_2 = 'combatir_custom_2',
    CONDUCIR_AUTOMOBIL = 'conducir_automobil',
    CONDUCIR_MAQUINARIA = 'conducir_maquinaria',
    CONTABILIDAD = 'contabilidad',
    DERECHO = 'derecho',
    DESCUBRIR= 'descrubir',
    DISFRAZARSE= 'disfrazarse',
    ELECTRICIDAD= 'electricidad',
    ENCANTO= 'encanto',
    EQUITACION= 'equitacion',
    ESCUCHAR= 'escuchar',
    ESQUIVAR= 'esquivar',
    HISTORIA= 'historia',
    INTIMIDAR= 'intimidar',
    JUEGOS_DE_MANOS= 'juegos_de_manos',
    LANZAR= 'lanzar',
    LENGUA_PROPIA= 'lengua_propia',
    OTRAS_LENGUAS_CUSTOM= 'otras_lenguas_custom',
    OTRAS_LENGUAS_CUSTOM_2= 'otras_lenguas_custom_2',
    OTRAS_LENGUAS_CUSTOM_3= 'otras_lenguas_custom_3',
    MECANICA= 'mecanica',
    MEDICINA= 'medicina',
    MITOS_DE_CTHULHU= 'mitos_de_cthulhu',
    NADAR= 'nadar',
    NATURALEZA= 'naturaleza',
    ORIENTARSE= 'orientarse',
    PERSUASION= 'persuasion',
    PILOTAR_CUSTOM= 'pilotar_custom',
    PRIMEROS_AUXILIOS= 'primeros_auxilios',
    PSICOANALISIS= 'psicoanalisis',
    PSICOLOGIA= 'psicologia',
    SALTAR= 'saltar',
    SEGUIR_RASTROS= 'seguir_rastros',
    SIGILO= 'sigilo',
    SUPERVIVENCIA_CUSTOM= 'supervivencia_custom',
    TASACION= 'tasacion',
    TREPAR= 'trepar';


export const habilidades = {
    antropologia: 1,
    armas_de_fuego_arma_corta:  20,
    armas_de_fuego_fusil_escopeta: 25,
    armas_de_fuego_custom: 0,
    arqueologia: 1,
    arte_artesania_custom: 5,
    arte_artesania_custom_2: 5,
    arte_artesania_custom_3: 5,
    buscar_libros: 20,
    cerrajeria: 1,
    charlateneria: 5,
    ciencia_custom: 1,
    ciencia_custom_2: 1,
    ciencia_custom_3: 1,
    ciencias_ocultas: 5,
    combatir_pelea: 25,
    combatir_custom: 0,
    combatir_custom_2: 0,
    conducir_automobil: 20,
    conducir_maquinaria: 1,
    contabilidad: 5,
    derecho: 5,
    descubrir: 25,
    disfrazarse: 5,
    electricidad: 10,
    encanto: 15,
    equitacion: 5,
    escuchar: 20,
    esquivar: 'des/2',
    historia: 5,
    intimidar: 15,
    juegos_de_manos: 10,
    lanzar: 20,
    lengua_propia: 'edu',
    otras_lenguas_custom: 1,
    otras_lenguas_ccustom_2: 1,
    otras_lenguas_custom_3: 1,
    mecanica: 10,
    medicina: 1,
    mitos_de_cthulhu: 0,
    nadar: 20,
    naturaleza: 10,
    orientarse: 10,
    persuasion: 10,
    pilotar_custom: 1,
    primeros_auxilios: 30,
    psicoanalisis: 1,
    psicologia: 10,
    saltar: 20,
    seguir_rastros: 10,
    sigilo: 20,
    supervivencia_custom: 10,
    tasacion: 5,
    trepar: 20
}

